### ISSUE TITLE
Even if I switch providers, LWE contacts openai api

### ISSUE THREAD

**Issue by wilenius** [llm-workflow-engine/lwe-plugin-provider-azure-openai-chat#1]
I've entered all Azure environment variables, and I have checked in other applications that they work. I switch providers in LWE, but I get errors from OpenAI's API instead of Azure's API. Is the plugin working for anybody?

**Comment by thehunmonkgroup** [comment]
I  believe https://github.com/llm-workflow-engine/lwe-plugin-provider-azure-openai-chat/commit/ac54c654e6834cb81268b495480d1d874ce1b137 will fix this, it looks like there were some structural changes to how the model information is passed.

`model` has been renamed to `deployment_name`.

I've added a `gpt-4-turbo` element to the default models list, giving your deployment that name should auto set the correct max tokens.

If the issue persists, feel free to reopen, and provide more detailed debugging information.
